import { Rocket, BarChart3, Crown, Coins, Shield, Zap, Search, PenTool, Layout, Layers } from 'lucide-react';

export const SERVICE_TIERS = [
  {
    id: 'tier-1',
    title: 'LaunchPad Site',
    subtitle: 'Tier I',
    price: 50000,
    description: 'For businesses getting started with their online presence.',
    icon: Rocket,
    image: '/images/services/tier-1.png',
    features: [
      '5–7 page responsive website',
      'Clean, modern design',
      'Mobile optimization',
      'Lead capture system',
      'Basic SEO setup',
      'Speed optimization',
    ],
  },
  {
    id: 'tier-2',
    title: 'Growth Engine',
    subtitle: 'Tier II',
    price: 110000,
    description: 'For businesses looking to scale and generate consistent leads.',
    icon: BarChart3,
    image: '/images/services/tier-2.png',
    popular: true,
    features: [
      '10–20 page custom website',
      'Conversion-focused UI/UX',
      'Strategic site architecture',
      'CMS integration',
      'Analytics & tracking setup',
      '2–3 revision cycles',
    ],
  },
  {
    id: 'tier-3',
    title: 'Authority Builder',
    subtitle: 'Tier III',
    price: 250000,
    description: 'For brands looking to dominate their market.',
    icon: Crown,
    image: '/images/services/tier-3.png',
    features: [
      'Complete brand identity system',
      'Fully custom UI/UX design',
      'Advanced interactions',
      'Conversion funnel design',
      'High-impact copywriting',
      'CRM & automation integration',
    ],
  },
  {
    id: 'tier-4',
    title: 'Revenue Architecture',
    subtitle: 'Tier IV',
    price: 500000,
    description: 'For businesses scaling aggressively.',
    icon: Coins,
    image: '/images/services/tier-4.png',
    features: [
      'End-to-end website & funnel ecosystem',
      'Multi-channel frameworks',
      'A/B testing setup',
      'Advanced analytics',
      'Conversion roadmap',
    ],
  },
];

export const ADDONS = [
  {
    id: 'seo-advanced',
    title: 'Advanced SEO Engine',
    price: 25000,
    description: 'Deep keyword research, technical SEO audit, and content strategy.',
    icon: Search,
  },
  {
    id: 'motion-cinematic',
    title: 'Cinematic Motion Pack',
    price: 35000,
    description: 'Bespoke WebGL and scroll-triggered animations.',
    icon: Zap,
  },
  {
    id: 'copy-premium',
    title: 'Premium Copywriting',
    price: 15000,
    description: 'Strategic conversion-focused copy (per 5 pages).',
    icon: PenTool,
  },
  {
    id: 'crm-automation',
    title: 'CRM & Automation',
    price: 45000,
    description: 'Full integration with HubSpot, Salesforce, or custom tools.',
    icon: Layers,
  },
  {
    id: 'maintenance-elite',
    title: 'Elite Maintenance',
    price: 10000,
    description: 'Monthly priority support and performance optimization.',
    icon: Shield,
    isMonthly: true,
  },
];
